spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/team202505?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user202505
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    database-platform: org.hibernate.dialect.MariaDBDialect

# log
logging:
  level:
    root: INFO
    uk.ac.ncl.team5project: DEBUG
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7

server:
  port: 8080 

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: MySecretKeyKK
  expiration: 86400000