server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/team05?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: user2025
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10

mybatis:
  type-aliases-package: uk.ac.ncl.team5.entities
  configuration:
    map-underscore-to-camel-case: true                 # user_name -> userName
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # SQL logging

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: MySecretKeyKK # Salt value for JWT
  expiration: 86400000 # 1 day in milliseconds